php:
- 7.2
before_script:
  - composer install
script: phpunit tests
deploy:
  provider: heroku
  app: project1-travis
  on: master
  skip_cleanup: true
  api_key:
    secure: VYyND8pimqWmpr9efkKLQFBwi6rXwG9xxHB4N0bo72A0wpxUCrKmLXuCI2mQdkkId6X9JmIgrNgp38UT8E2tTjpRTaKYfsU7IVbQ43NO9oPWFSbxatCsNW0z8t7ktFxeR1rA4SZheph4ZdAM29oFOJEi/WXd/PVEhFVn3FHWOeyQFxGzbe3jLbOGE8++3BRkmPAKRs+0+Zmfni+CsUJJJXQqpNejLjXo83sPV6gt5LykchlPj5J5dW/yNjpgYPB6ZGVSw75H3hlo/k7JKNaoPJ0psPFCfCc63bmEW2YcDt2B+zw5wJ8rw18qNJFt6FfNGEYEJplMJUH1jurOFrLyl51RVPAtR0QhILZD5VAaB/9QU/9vL7P+Rg9vM7ASLUUixa/mSxwJcCLj9ieaV9mtvoBEkT8Sdvsr/9S6RGxJBPCWGxPo4jAi5jH3yPAidFhqmTMrJLhvQMNC6z2JEp+3uriLMlh3bcXNtQ05PdZOz7BIVlLwXEtK4GU8lB75J50tqI/YqLxES7RpymwIAVawfiYWdY6UQSNaVEkxNFfiFhUTrS0jRNiH2z0/ju5Fu7HI8vUqvZ+jkwx2ku7qDFIJwXUygjIEadjl2cFkEEgDV+/pXaCD8oBMulAvCCzPILoYtWfpr6g20CpPhlCihuGwypHMcoDc8cnR6uTcG7Z8/tY=
