language: php
php:
- 7.2
before_script:
  - composer install
script: phpunit tests
deploy:
  provider: heroku
  app: project1-travis
  on: master
  skip_cleanup: true
  api_key:
    secure: fwGH/Yx6wDfnbeM1RmDM/XoGbQlE7fUQ5Uz2cKMuFaNQY27Q4W4fCE4YiS/LQdD86LOJyu960vSwA4A1X6Q77MI/g6Ns2lhLaZJPlv5wUR2zWL+cd8mEp3VwEzKgWHbOj7wECu9rY/twBeqxQY0K5wq9i/STbwmmh3vPJkhAYJR3Nz/2A0bkGArPainB03lG4iuXs6eNdYdv0DXWcFgCSNDodnP59ycXHcfy0XY9Rod/VaVRvG9CliCPgHrTR+vTcPeFkwXHwStvBbzxGZuK3kqq9XsGn0VbUvv65uOeQFn/NX1ZhTYnK9bavdn0j3l1C4YjLOb5scBGCd2K0tskl53zmBPXivaO97aRp9iS0Vjw1kEZu7svKl3e/UM6MQ9xBXhWdsTrP2BZahVPU5I0ZjWU9cAZoNbaROG/6reC7K3rjJAPtta5Jhz6EacbGY+JzMBVXl1BmXd/qHEysSoJY8D+guyAvpfpJD34b2QuRibVQUseGprKJPyaVHQUAWKytfEAf8o13EMHfERoQIV666NrD2pGDkAh36AeApwJ6KMTJuwiP/MD3YpgbSkIlHaZRfOsmSyZ0WFo+iVzgI+oi3s36ldGvsYWlejDa6zVPfN3ofn3IhPlKzT2khGDJ1F6y3IpOLbJGqTBXnC2GGAp4Hv0wkRspLQz7T3oCksPlhI=
